### ISSUE TITLE
你好，cs回显如下信息，是没过杀软吗。

### ISSUE THREAD

**Issue by jielansudo** [mstxq17/FrpProPlugin#1]
` [service.go:101] login to server failed: dial tcp x.x.x.x:7002: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. dial tcp x.x.x.x:7002: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`  正常环境经过测试，可以正常通信

**Comment by mstxq17** [comment]
你是用的我的release的编译好的服务端吗。贴一下你使用的配置

**Comment by jielansudo** [comment]
对的，使用你release的客户端，frpc.ini配置如上




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月23日(星期二) 下午5:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mstxq17/FrpProPlugin] 你好，cs回显如下信息，是没过杀软吗。 (#1)





 
你是用的我的release的编译好的服务端吗。贴一下你使用的配置

**Comment by mstxq17** [comment]
我这边测试是正常的，我增加了使用说明，你可以参考下来配置。现在客户端确实被查杀了，可能是杀软屏蔽了，我有空就更新下。
如果你那边无杀软环境，依然不行，贴上配置和具体什么平台的frps客户端

**Comment by jielansudo** [comment]
无杀软环境是可以正常执行的，我已经找到问题所在了。感谢回复

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xq17 ***@***.***&gt;
发送时间: 2021年3月23日 18:35
收件人: mstxq17/FrpProPlugin ***@***.***&gt;
抄送: sudo ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[mstxq17/FrpProPlugin] 你好，cs回显如下信息，是没过杀软吗。 (#1)
